### ISSUE TITLE
Sidebar color and size 

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Sociology#20]
@LabLayers Hey Victor the size and color for the sidebars that are on all of the sites undergrad and grad pages still needs to be fixed. Thanks!

These sites are currently live with it: 
 @www.cla.temple.edu/asian-studies/  
www.cla.temple.edu/sociology/  
www.cla.temple.edu/american-studies/ 
www.cla.temple.edu/global-studies/

**Comment by pixelyunicorn** [comment]
Does it look better now?
![image](https://user-images.githubusercontent.com/607807/27609395-a26c221e-5b58-11e7-97b6-ff163af7fcdb.png)

**Comment by CVE82** [comment]
Yessssss that's the ticket, thank you!!! Do yo think we could make it a wee bit more narrow so the content is the main focus?

**Comment by tu-chill** [comment]
I'm curious about a few things. 

1) I'm bringing @ZMcGroarty  into the conversation because increasing collaboration is one of my PDP goals for this year.

2) Visually I'd like to shift the focus away from the sidebar and onto the primary content. Here is an obvious way

![screen shot 2017-06-28 at 9 34 42 am](https://user-images.githubusercontent.com/12816361/27655171-6e40e212-5c12-11e7-88e8-eba90c7acf78.png)

We can pseudo-select the first paragraph and increase font-size and line-height.

Remove the Heading/Call to Action "Contact Us" Because I don't think we should encourage visitors to contact through phone or email. 

I am flat.  I say we set the background color for the page sidebar to be white and thin out the hard rules and gray up the color for text.

3) I am also interested in Codepen.io exported as gists. I think It can become a good way for us all to collaborate.

**Comment by CVE82** [comment]
I want to do this, it looks great and makes sense. Which equals a win!

**Comment by ZMcGroarty** [comment]
I think it works perfectly. Simple and clean.
